apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.imagePacientes.name }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.imagePacientes.EXPOSE_PORT }}
    targetPort: {{ .Values.imagePacientes.EXPOSE_PORT }}
    name: {{ .Values.imagePacientes.name }}
  selector:
    role: {{ .Values.imagePacientes.name }}

