apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.application.name}}
  name: {{.Values.application.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.application.name}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.application.name}}
        role: {{.Values.application.name}}
    spec:
      containers:
        - image: {{.Values.imageAtencion.repository}}
          imagePullPolicy: {{.Values.imageAtencion.pullPolicy}}
          name: {{ .Values.imageAtencion.name }}
          ports:
            - containerPort: {{.Values.imageAtencion.EXPOSE_PORT}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.imageAtencion.EXPOSE_PORT}}
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            limits:
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 600Mi
          env:
            - name: EXPOSE_PORT
              value: {{.Values.imageAtencion.EXPOSE_PORT | quote}}
            {{- range $key, $val := .Values.envVars}}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
        - image: {{.Values.imageAutentificacion.repository}}
          imagePullPolicy: {{.Values.imageAutentificacion.pullPolicy}}
          name: {{ .Values.imageAutentificacion.name }}
          ports:
            - containerPort: {{.Values.imageAutentificacion.EXPOSE_PORT}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.imageAutentificacion.EXPOSE_PORT}}
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            limits:
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 600Mi
          env:
            - name: EXPOSE_PORT
              value: {{.Values.imageAutentificacion.EXPOSE_PORT | quote}}
            {{- range $key, $val := .Values.envVars}}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
        - image: {{.Values.imageDiagnosticos.repository}}
          imagePullPolicy: {{.Values.imageDiagnosticos.pullPolicy}}
          name: {{ .Values.imageDiagnosticos.name }}
          ports:
            - containerPort: {{.Values.imageDiagnosticos.EXPOSE_PORT}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.imageDiagnosticos.EXPOSE_PORT}}
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            limits:
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 600Mi
          env:
            - name: EXPOSE_PORT
              value: {{.Values.imageDiagnosticos.EXPOSE_PORT | quote}}
            {{- range $key, $val := .Values.envVars}}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
        - image: {{.Values.imagePacientes.repository}}
          imagePullPolicy: {{.Values.imagePacientes.pullPolicy}}
          name: {{ .Values.imagePacientes.name }}
          ports:
            - containerPort: {{.Values.imagePacientes.EXPOSE_PORT}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.imagePacientes.EXPOSE_PORT}}
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            limits:
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 600Mi
          env:
            - name: EXPOSE_PORT
              value: {{.Values.imagePacientes.EXPOSE_PORT | quote}}
            {{- range $key, $val := .Values.envVars}}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
        - image: {{.Values.imagePruebas.repository}}
          imagePullPolicy: {{.Values.imagePruebas.pullPolicy}}
          name: {{ .Values.imagePruebas.name }}
          ports:
            - containerPort: {{.Values.imagePruebas.EXPOSE_PORT}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.imagePruebas.EXPOSE_PORT}}
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            limits:
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 600Mi
          env:
            - name: EXPOSE_PORT
              value: {{.Values.imagePruebas.EXPOSE_PORT | quote}}
            {{- range $key, $val := .Values.envVars}}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
        - image: {{.Values.imageResultados.repository}}
          imagePullPolicy: {{.Values.imageResultados.pullPolicy}}
          name: {{ .Values.imageResultados.name }}
          ports:
            - containerPort: {{.Values.imageResultados.EXPOSE_PORT}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.imageResultados.EXPOSE_PORT}}
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            limits:
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 600Mi
          env:
            - name: EXPOSE_PORT
              value: {{.Values.imageResultados.EXPOSE_PORT | quote}}
            {{- range $key, $val := .Values.envVars}}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
      restartPolicy: Always
      imagePullSecrets:
          - name: regcred
status: {}