apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.imageAtencion.EXPOSE_PORT }}
    targetPort: {{ .Values.imageAtencion.EXPOSE_PORT }}
    name: {{ .Values.imageAtencion.name }}
  - protocol: TCP
    port: {{ .Values.imageAutentificacion.EXPOSE_PORT }}
    targetPort: {{ .Values.imageAutentificacion.EXPOSE_PORT }}
    name: {{ .Values.imageAutentificacion.name }}
  - protocol: TCP
    port: {{ .Values.imageDiagnosticos.EXPOSE_PORT }}
    targetPort: {{ .Values.imageDiagnosticos.EXPOSE_PORT }}
    name: {{ .Values.imageDiagnosticos.name }}
  - protocol: TCP
    port: {{ .Values.imagePacientes.EXPOSE_PORT }}
    targetPort: {{ .Values.imagePacientes.EXPOSE_PORT }}
    name: {{ .Values.imagePacientes.name }}
  - protocol: TCP
    port: {{ .Values.imagePruebas.EXPOSE_PORT }}
    targetPort: {{ .Values.imagePruebas.EXPOSE_PORT }}
    name: {{ .Values.imagePruebas.name }}
  - protocol: TCP
    port: {{ .Values.imageResultados.EXPOSE_PORT }}
    targetPort: {{ .Values.imageResultados.EXPOSE_PORT }}
    name: {{ .Values.imageResultados.name }}
  selector:
    role: {{ .Values.application.name }}

