apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.imageWebApp.name}}
  name: {{.Values.imageWebApp.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.imageWebApp.name}}
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.imageWebApp.name}}
        role: {{.Values.imageWebApp.name}}
    spec:
      containers:
        - image: {{.Values.imageWebApp.repository}}
          imagePullPolicy: {{.Values.imageWebApp.pullPolicy}}
          name: {{ .Values.imageWebApp.name }}
          ports:
            - containerPort: {{.Values.imageWebApp.EXPOSE_PORT}}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health/liveness
          #     port: {{.Values.imageWebApp.EXPOSE_PORT}}
          #   initialDelaySeconds: 15
          #   periodSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health/readiness
          #     port: {{.Values.imageWebApp.EXPOSE_PORT}}
          #   initialDelaySeconds: 15
          #   periodSeconds: 5
          resources:
            limits:
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 600Mi
          env:
            - name: EXPOSE_PORT
              value: {{.Values.imageWebApp.EXPOSE_PORT | quote}}
            {{- range $key, $val := .Values.envVars}}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
      restartPolicy: Always
status: {}