apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.imageTransferencias.name}}
  name: {{.Values.imageTransferencias.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.imageTransferencias.name}}
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.imageTransferencias.name}}
        role: {{.Values.imageTransferencias.name}}
    spec:
      containers:
        - image: {{.Values.imageTransferencias.repository}}
          imagePullPolicy: {{.Values.imageTransferencias.pullPolicy}}
          name: {{ .Values.imageTransferencias.name }}
          ports:
            - containerPort: {{.Values.imageTransferencias.EXPOSE_PORT}}
              protocol: TCP
          resources:
            limits:
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 600Mi
          env:
            - name: EXPOSE_PORT
              value: {{.Values.imageTransferencias.EXPOSE_PORT | quote}}
            {{- range $key, $val := .Values.envVars}}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
      restartPolicy: Always
status: {}